using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyHealthManager : MonoBehaviour
{
    #region Public Variables 
    #endregion 

    #region Private Variables
    [SerializeField] private float _enemyMaxHealth;
    [SerializeField] private float _enemyCurrentHealth;
    private bool _isDead = false;
    #endregion

    #region Unity Methods
    // Start is called before the first frame update
    void Start()
    {
        SetEnemyHealth();
    }

    // Update is called once per frame
    void Update()
    {
        EnemyDeath();
    }
    #endregion

    #region Public Methods
    public void TakeDamage(float pDamage)
    {
        _enemyCurrentHealth -= pDamage;
    }
    #endregion 

    #region Private Methods 
    private void SetEnemyHealth()
    {
        _enemyCurrentHealth = _enemyMaxHealth;
        _isDead = false;
    }

    private void EnemyDeath()
    {
        if (_enemyCurrentHealth <= 0)
            _isDead = true;

        if (_isDead)
            Destroy(gameObject);
    }
    #endregion

    #region Coroutines
    #endregion
}
